name: Continuous Integration

on:
  pull_request:
  push:
    branches: [ dev ]

jobs:
  run-tests:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install ci

      - name: Setup Database
        env:
          DB_NAME: testdb.db
        run: node src/database/databaseSetup.js
      
      - name: Locate Database Files
        run: |
          echo "Current Path: $(pwd)"
          echo "--- Searching for all .db files ---"
          find . -name "*.db" -exec ls -lh {} +
          echo "--- End of search ---"

      - name: Run mocha BDD testing
        id: database-testing
        env:
          DB_NAME: testdb.db
        run: |
          npm test
          
      - name: Run Script-based tests
        env:
          DB_NAME: testdb.db
        run: |
          npx tsx Testing/test_schema.ts
          npx tsx Testing/runQuery_test.ts
          npx tsx Testing/getQuery_test.ts
          npx tsx Testing/outbox_test.ts