name: Continuous Integration

on:
  pull_request:
  push:
    branches: [ dev ]

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install ci

  run-tests:
    name: database tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
        npm install ci
        npm install --save-dev tsx

      - name: Setup Database
        env:
          DB_NAME: testdb.db
        run: node src/database/databaseSetup.js
      
      - name: Locate Database Files
        run: |
          echo "Current Path: $(pwd)"
          echo "--- Searching for all .db files ---"
          find . -name "*.db" -exec ls -lh {} +
          echo "--- End of search ---"

      - name: Run database function tests
        id: database-testing
        env:
          DB_NAME: testdb.db
        run: |
          npx tsx Testing/test_schema.ts
          npx tsx Testing/runQuery_test.ts
          npx tsx Testing/getQuery_test.ts
          npx tsx Testing/outbox_test.ts
          npx tsx Testing/userWithOutbox_test.ts